export const APPWRITE_SECRET_KEY = process.env.NEXT_APPWRITE_SECRET_KEY!

export const APPWRITE_ENDPOINT = process.env.NEXT_APPWRITE_ENDPOINT!
export const APPWRITE_PROJECT_ID = process.env.NEXT_APPWRITE_PROJECT_ID!
export const DATABASE_ID = process.env.NEXT_APPWRITE_DATABASE_ID!
export const STORAGE_ID = process.env.NEXT_APPWRITE_STORAGE_ID!

export const APPWRITE_ATTACHMENTS_ID = process.env.NEXT_APPWRITE_ATTACHMENTS_ID!
export const APPWRITE_BLOCKED_USERS_ID =
  process.env.NEXT_APPWRITE_BLOCKED_USERS_ID!
export const APPWRITE_CHANNEL_ADMINS_ID =
  process.env.NEXT_APPWRITE_CHANNEL_ADMINS_ID!
export const APPWRITE_CHANNEL_OPTIONS_ID =
  process.env.NEXT_APPWRITE_CHANNEL_OPTIONS_ID!
export const APPWRITE_CHANNEL_SUBSCRIBERS_ID =
  process.env.NEXT_APPWRITE_CHANNEL_SUBSCRIBERS_ID!
export const APPWRITE_CHANNELS_ID = process.env.NEXT_APPWRITE_CHANNELS_ID!
export const APPWRITE_CONVERSATION_OPTIONS_ID =
  process.env.NEXT_APPWRITE_CONVERSATION_OPTIONS_ID!
export const APPWRITE_CONVERSATIONS_ID =
  process.env.NEXT_APPWRITE_CONVERSATIONS_ID!
export const APPWRITE_GROUP_MEMBERS_ID =
  process.env.NEXT_APPWRITE_GROUP_MEMBERS_ID!
export const APPWRITE_GROUP_OPTIONS_ID =
  process.env.NEXT_APPWRITE_GROUP_OPTIONS_ID!
export const APPWRITE_GROUPS_ID = process.env.NEXT_APPWRITE_GROUPS_ID!
export const APPWRITE_MESSAGES_ID = process.env.NEXT_APPWRITE_MESSAGES_ID!
export const APPWRITE_REACTIONS_ID = process.env.NEXT_APPWRITE_REACTIONS_ID!
export const APPWRITE_SETTINGS_ID = process.env.NEXT_APPWRITE_SETTINGS_ID!
export const APPWRITE_USERS_ID = process.env.NEXT_APPWRITE_USERS_ID!
