export const ERROR = {
  INVALID_EMAIL: "INVALID_EMAIL",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
  EMAIL_NOT_REGISTERED: "EMAIL_NOT_REGISTERED",

  PASSWORD_CONTAIN_LOWERCASE: "PASSWORD_CONTAIN_LOWERCASE",
  PASSWORD_CONTAIN_UPPERCASE: "PASSWORD_CONTAIN_UPPERCASE",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_CONTAIN_NUMBER: "PASSWORD_CONTAIN_NUMBER",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_DONT_MATCH: "PASSWORD_DONT_MATCH",
  CONFIRM_PASSWORD_REQUIRED: "CONFIRM_PASSWORD_REQUIRED",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZE: "UNAUTHORIZE",

  FIRST_NAME_REQUIRED: "FIRST_NAME_REQUIRED",
  FIRST_NAME_TOO_LONG: "FIRST_NAME_TOO_LONG",
  LAST_NAME_TOO_LONG: "LAST_NAME_TOO_LONG",
  USERNAME_REQUIRED: "USERNAME_REQUIRED",
  USERNAME_TOO_LONG: "USERNAME_TOO_LONG",
  USERNAME_ALREADY_EXIST: "USERNAME_ALREADY_EXIST",
  INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",
  GENDER_REQUIRED: "GENDER_REQUIRED",
  INVALID_GENDER: "INVALID_GENDER",
  BIO_TOO_LONG: "BIO_TOO_LONG",

  INPUT_IS_NOT_FILE: "INPUT_IS_NOT_FILE",
  INVALID_IMAGE_TYPE: "INVALID_IMAGE_TYPE",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",

  OTP_REQUIRED: "OTP_REQUIRED",

  COMPLETE_PROFILE_FIRST: "COMPLETE_PROFILE_FIRST",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
} as const
