export const ERROR = {
  INTERNAL_SERVER_ERROR: "error.common.internal_server_error",
  UNAUTHORIZE: "error.common.unauthorized",
  NOT_ALLOWED: "error.common.not_allowed",
  INVALID_CREDENTIALS: "error.common.invalid_credentials",
  INVALID_TYPE: "error.common.invalid_type",
  REQUIRED: "error.common.required",

  INVALID_EMAIL: "error.email.invalid",
  EMAIL_REQUIRED: "error.email.required",
  EMAIL_TOO_LONG: "error.email.too_long",
  EMAIL_ALREADY_EXIST: "error.email.already_exist",
  EMAIL_NOT_REGISTERED: "error.email.not_registered",
  EMAIL_UNVERIFIED: "error.email.unverified",
  EMAIL_ALREADY_VERIFIED: "error.email.already_verified",

  PASSWORD_SHOULD_CONTAIN_LOWERCASE: "error.password.contain_lowercase",
  PASSWORD_SHOULD_CONTAIN_UPPERCASE: "error.password.contain_uppercase",
  PASSWORD_TOO_SHORT: "error.password.too_short",
  PASSWORD_TOO_LONG: "error.password.too_long",
  PASSWORD_SHOULD_CONTAIN_NUMBER: "error.password.contain_number",
  PASSWORD_REQUIRED: "error.password.required",
  PASSWORD_DONT_MATCH: "error.password.dont_match",
  CONFIRM_PASSWORD_REQUIRED: "error.password.confirm_password_required",

  USERNAME_REQUIRED: "error.username.required",
  USERNAME_TOO_SHORT: "error.username.too_short",
  USERNAME_TOO_LONG: "error.username.too_long",
  USERNAME_ALREADY_EXIST: "error.username.already_exist",
  INVALID_USERNAME_FORMAT: "error.username.invalid_format",

  NAME_REQUIRED: "error.name.required",
  NAME_TOO_LONG: "error.name.too_long",
  NAME_TOO_SHORT: "error.name.too_short",

  GENDER_REQUIRED: "error.gender.required",
  INVALID_GENDER: "error.gender.invalid",

  BIO_TOO_LONG: "error.bio.too_long",

  TOKEN_REQUIRED: "error.token.required",
  INVALID_TOKEN: "error.token.invalid",
  TOKEN_EXPIRED: "error.token.expired",

  INVALID_IMAGE_TYPE: "error.image.invalid_type",
  IMAGE_TOO_LARGE: "error.image.too_large",

  OTP_REQUIRED: "error.otp.required",
  INVALID_CODE_OR_OTP_ID: "error.otp.invalid_code_or_otp_id",

  COMPLETE_PROFILE_FIRST: "error.profile.complete_first",
  CREATE_PROFILE_FIRST: "error.profile.create_first",
  PROFILE_NOT_FOUND: "error.profile.not_found",
  PROFILE_ALREADY_CREATED: "error.profile.already_created",

  BLOCKED_USER_NOT_FOUND: "error.blocked_user.not_found",
  USER_ALREADY_BLOCKED: "error.blocked_user.already_blocked",
  CANNOT_BLOCK_IT_SELF: "error.blocked_user.cannot_block_it_self",

  USER_NOT_FOUND: "error.user.not_found",
  PRIVATE_CHAT_OPTION_NOT_FOUND: "error.private_chat_option.not_found",
  USER_ID_REQUIRED: "error.user_id_required",

  GROUP_NAME_REQUIRED: "error.group.name_required",
  GROUP_NAME_TOO_SHORT: "error.group.name_too_short",
  GROUP_NAME_TOO_LONG: "error.group.name_too_long",
  GROUP_NAME_DUPLICATED: "error.group.name_duplicated",
  GROUP_DESC_TOO_LONG: "error.group.desc_too_long",
  GROUP_TYPE_REQUIRED: "error.group.type_required",
  INVALID_GROUP_TYPE: "error.group.invalid_type",
  INVALID_MEMBER_ID_TYPE: "error.group.invalid_member_id_type",
  INVALID_MEMBER_IDS_TYPE: "error.group.invalid_member_ids_type",
  ADD_BLOCKED_USERS_NOT_ALLOWED: "error.group.add_blocked_users_not_allowed",
  ADDDED_BY_BLOCKED_USER_NOT_ALLOWED:
    "error.group.added_by_blocked_user_not_allowed",
  MEMBER_ID_NOT_FOUND: "error.group.member_id_not_found",
  GROUP_NOT_FOUND: "error.group.not_found",
  GROUP_OWNER_NOT_FOUND: "error.group.owner_not_found",

  JOIN_CODE_REQUIRED: "error.join_group.join_code_required",
  INVALID_JOIN_CODE: "error.join_group.invalid_join_code",
  ALREADY_MEMBER: "error.join_group.already_member",
  NOT_GROUP_MEMBER: "error.join_group.not_member",
  ONLY_ADMIN_ADD_MEMBER: "error.join_group.only_admin_add_member",
  ADDED_USER_ALREADY_MEMBER: "error.join_group.added_user_already_member",
  ADDED_USER_NOT_FOUND: "error.join_group.added_user_not_found",
  ONLY_ADMIN_REMOVE_MEMBER: "error.join_group.only_admin_remove_member",
  REMOVED_USER_NOT_FOUND: "error.join_group.removed_user_not_found",
  REMOVED_USER_IS_NOT_MEMBER: "error.join_group.removed_user_is_not_member",
  USER_IS_NOT_MEMBER: "error.join_group.user_is_not_member",
  USER_ALREADY_ADMIN: "error.join_group.user_already_admin",
  USER_IS_NOT_ADMIN: "error.join_group.user_is_not_admin",
  THE_ONLY_ONE_MEMBER: "error.join_group.only_one_member",

  CHANNEL_NAME_REQUIRED: "error.channel.name_required",
  CHANNEL_NAME_TOO_SHORT: "error.channel.name_too_short",
  CHANNEL_NAME_TOO_LONG: "error.channel.name_too_long",
  CHANNEL_NAME_DUPLICATED: "error.channel.name_duplicated",
  CHANNEL_DESC_TOO_LONG: "error.channel.desc_too_long",
  CHANNEL_TYPE_REQUIRED: "error.channel.type_required",
  INVALID_CHANNEL_TYPE: "error.channel.invalid_type",
  CHANNEL_NAME_ALREADY_EXIST: "error.channel.name_already_exist",
  CHANNEL_NOT_FOUND: "error.channel.not_found",
  CHANNEL_OWNER_NOT_FOUND: "error.channel.owner_not_found",
  ONLY_ADMIN_CAN_ADD_ADMIN: "error.channel.only_admin_can_add_admin",
  ONLY_ADMIN_CAN_REMOVE_ADMIN: "error.channel.only_admin_can_remove_admin",
  USER_IS_NOT_SUBSCRIBER: "error.channel.user_is_not_subscriber",
  ALREADY_SUBSCRIBER: "error.channel.already_subscriber",

  NOTIFICATION_REQUIRED: "error.settings.required",
  INVALID_NOTIFICATION_TYPE: "error.settings.invalid_type",
  INVALID_TIME_FORMAT: "error.settings.invalid_time_format",
  INVALID_LANGUAGE: "error.settings.invalid_language",

  MESSAGE_REQUIRED: "error.message.required",
  MESSAGE_TOO_LONG: "error.message.too_long",
  PARENT_MESSAGE_TOO_LONG: "error.message.parent_message_too_long",
  INVALID_MESSAGE_STATUS: "error.message.invalid_status",
  ROOM_ID_REQUIRED: "error.message.room_id_required",
  ROOM_ID_DUPLICATED: "error.message.room_id_duplicated",
  ATTACHMENT_TOO_LARGE: "error.message.attachment_too_large",
  MESSAGE_NOT_FOUND: "error.message.not_found",
  PARENT_MESSAGE_NOT_IN_ROOM: "error.message.parent_message_not_in_room",
  SHOULD_HAVE_MESSAGE_OR_ATTACHMENT:
    "error.message.should_have_message_or_attachment",
  UPDATE_DELETED_MESSAGE_NOT_ALLOWED:
    "error.message.update_deleted_message_not_allowed",
  MESSAGE_ALREADY_DELETED: "error.message.already_deleted",
  CANNOT_SEND_MESSAGE_TO_BLOCKED_USER:
    "error.message.cannot_send_message_to_blocked_user",
  NO_UNREAD_MESSAGE: "error.message.no_unread_message",

  ROOM_NOT_FOUND: "error.room.not_found",
  ROOM_ALREADY_PINNED: "error.room.already_pinned",
  ROOM_NOT_PINNED: "error.room.not_pinned",
  CANNOT_PINNED_ARCHIVED_ROOM: "error.room.cannot_pinned_archived_room",
  ROOM_ALREADY_ARCHIVED: "error.room.already_archived",
  ROOM_NOT_ARCHIVED: "error.room.not_archived",
  CANNOT_DELETE_JOINED_GROUP: "error.room.cannot_delete_joined_group",
  CANNOT_DELETE_SUBSCRIBED_CHANNEL:
    "error.room.should_unsubscribe_channel_first",
  INVALID_ROOM_TYPE: "error.room.invalid_type",
} as const
