export const ERROR = {
  INVALID_EMAIL: "INVALID_EMAIL",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
  EMAIL_NOT_REGISTERED: "EMAIL_NOT_REGISTERED",

  PASSWORD_CONTAIN_LOWERCASE: "PASSWORD_CONTAIN_LOWERCASE",
  PASSWORD_CONTAIN_UPPERCASE: "PASSWORD_CONTAIN_UPPERCASE",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_CONTAIN_NUMBER: "PASSWORD_CONTAIN_NUMBER",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_DONT_MATCH: "PASSWORD_DONT_MATCH",
  CONFIRM_PASSWORD_REQUIRED: "CONFIRM_PASSWORD_REQUIRED",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZE: "UNAUTHORIZE",

  OTP_REQUIRED: "OTP_REQUIRED",
} as const
